### PR TITLE
Add `script_prefix` argument

### LINKED ISSUE #148: Additional prefix for topics
**Is your feature request related to a problem? Please describe.**
Gen1 devices by default kept all their topics under the "shellies" prefix. The announce system was also done under this prefix, which means that everything was kept nice and tidy :)
This had the additional benefit of security, as it allowed for an ACL to be used giving all Shelly devices access to just the shellies topic and below, and everything worked perfectly.

With Gen2 this is not so by default - the topics are created at root level. 
We can easily solve this by specifying a common prefix in every device, forcing it to be under a common root like Gen1 used to do.
However the shellies_discovery_gen2 is creating topics on the root - namely the "shellies_discovery" and "shellies_discovery_script".
Not only this is not "nice and tidy" anymore, it breaks functionality when using the ACL like before, since the Shelly devices wouldn't have access to these topics.

**Describe the solution you'd like**
I'm not entirely sure what the cleanest solution would be.
Currently, there are 3 areas that need tweaking if we use a prefix in the topic name:
1) the "device_ids" section (already documented and working fine)
2) the 'src':'shellies_discovery' field in the Shelly.GetConfig payload (e.g. src':'shellies/shellies_discovery) for the shellies_announce_gen2 automation. This is an easy edit in the automations file.
3) the "shellies_discovery_gen2.py" script - this is the tricky part, as it hardcodes the locations for "shellies_discovery" and "shellies_discovery_script". Perhaps a config parameter? Then we can add it to service call in the shellies_discovery_gen2 automation.

I think a config parameter probably is the smallest change/impact to achieve this...
But perhaps there is an even better way.

**Additional context**
Food for thought: if we setup things with the "everything under one root" approach, perhaps it would make it possible for the script to autodiscover devices, since it could enumerate everything under that prefix, instead of the user having to manually specify devices ids, achieving similar behavior as gen1 (which would be quite nice)

### PR DESCRIPTION
**Pull request by bieniu**
Closes #148

### CODE REVIEW

**Comment by LordShadowen** [comment]
Hi,

thanks for adding this feature.
However, it didn't work, and upon debugging, spotted two problems:

Line 1834 was missing the { } around TOPIC_SHELLIES_DISCOVERY_SCRIPT
The topic got created as literally "shellies/TOPIC_SHELLIES_DISCOVERY_SCRIPT"
`
script_topic = f"{script_prefix}/{TOPIC_SHELLIES_DISCOVERY_SCRIPT}"
`


In line 1832 I had to do this:
`
topic = encode_config_topic(f"{script_prefix}/{device_id}/rpc")
`

I think that's because the "src" of the message coming from the device is the client ID, and not the MQTT prefix.
And even then, this only works because they match... 

Please check if this makes sense to you....

**Comment by bieniu** [comment]
> The topic got created as literally "shellies/TOPIC_SHELLIES_DISCOVERY_SCRIPT"

Eeeeh I'm blind, thanks.

> In line 1832 I had to do this:
> `topic = encode_config_topic(f"{script_prefix}/{device_id}/rpc")`

No, you should change the device IDs (in the device web panel and in the automation) and change `src` in your Shellies Discovery automations.

**Comment by LordShadowen** [comment]
> No, you should change the device IDs (in the device web panel and in the automation) and change `src` in your Shellies Discovery automations.

I've tried that, but it doesn't work properly. It looks like any message published by the Shelly device always uses src="[original device id]", as defined in the Settings > Device Info > Device ID. This field is *not* editable.
What can be edited is the "Client ID" field of MQTT web config page... but it doesn't use that.
So in this section:

```
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
```

The id will always be that original ID, without any prefix.
As a consequence, I never see the shelies_discovery_script topic being created like it used to and there's always a topic on the root anyway....

Thoughts?

**Comment by bieniu** [comment]
Hmmm they changed field name from `Device ID` to `MQTT Prefix’.

776906AB-E779-45A5-98A4-EFF75421802A

**Comment by LordShadowen** [comment]
Right - but more importantly, this value is not used for src in their MQTT messages. It's always the Device ID as defined in the Device Info

**Comment by bieniu** [comment]
Have you edited your automations?

**Comment by LordShadowen** [comment]
Just to be clear, this is what I see

MQTT:

image

Device Info:

image

**Comment by LordShadowen** [comment]
> Have you edited your automations?

```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shellies/shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shellies/shellyplus2pm-blabla
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shellies/shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
      script_prefix: "shellies"
      qos: 2
```

**Comment by bieniu** [comment]
Looks good. And where is the problem? The device publishes to the wrong topic?

**Comment by bieniu** [comment]
BTW You should not change Client ID.

**Comment by LordShadowen** [comment]
> BTW You should not change the Client ID.

I know - this was just for testing... 

This is what fails:

1) This gets published on the topic named after the Device ID, created on root, instead of being under shellies:
`{"id": 1, "src": shellies/shelies_discovery_script, "method": "Script.SetConfig", "params": {"id": 1, "config": {"enable": true}}}`

2) The script doesn't get created on the device

3) There is no topic with the name shellies_discovery_script created anywhere

4) Certain entities, like Firmware always stay in the "Unknown" state

All of this works fine if I do the edit you said not to do (in line 1832):  
`topic = encode_config_topic(f"{script_prefix}/{device_id}/rpc")`

**Comment by bieniu** [comment]
Please open new issue and attach a debug log for python_script component.

**Comment by LordShadowen** [comment]
Need some help - I know how to set the level to debug for the python_script, but don't know how to have that split to its own file without all the other logging from HA....

**Comment by bieniu** [comment]
There is no way to split the log file. Set the default level to warning and for the python_ script to debug, restart HA, run announce automation and catch the log file.

**Comment by LordShadowen** [comment]
Here you go.
I did a cleanup first to start fresh and also changed to the prefix "shelliesg2" to make things even more separate from any Gen1 stuff.

[python_script.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/10667932/python_script.log)

**Comment by bieniu** [comment]
Open an issue here https://github.com/bieniu/ha-shellies-discovery-gen2/issues/new/choose

This is not a good place to continue this case.

**Pull request merged**
