### PR TITLE
Add support for monophase profile for Pro 3EM

### PR DESCRIPTION
**Pull request by bieniu**
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/338

### CODE REVIEW

**Comment by bieniu** [comment]
@jpatriarca Could you test this change?

**Comment by jpatriarca** [comment]
Hi @bieniu, apologies for the late reply and happy new year. Tested the changed script and it’s unable to detect the device. Reverting to the production one, it works as expected but provides unknown values, as reported. Is there any debug or tests you can direct me to do and help you develop the changes?

**Comment by bieniu** [comment]
> Tested the changed script and it’s unable to detect the device.

What do you mean? Were there errors in the log?


> Is there any debug or tests you can direct me to do and help you develop the changes?

image

**Comment by jpatriarca** [comment]
@bieniu, just checked the logs and I got this with your new version of the script:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shellies_discovery_gen2.py", line 1, in <module>
NameError: name 'false' is not defined
```
Might be the reason why running the new script my Pro 3EM don't appear with MQTT entities (I deleted everything I had for this device)

**Comment by bieniu** [comment]
Did you install the script correctly? You must use the file from this link: https://raw.githubusercontent.com/bieniu/ha-shellies-discovery-gen2/539ba7f759a130b3a1877d3ba374a69dfccb97d4/python_scripts/shellies_discovery_gen2.py

**Comment by jpatriarca** [comment]
Thanks for your suggestion. Effectively I grabbed the new version wrong and now I can see the values for each channel, as expected. But still seeing some entities appearing related with Phase A/B/C. Will continue to test it along the day and will provide you with further informations

**Comment by jpatriarca** [comment]
@bieniu, would like to report that, in additional with EM0-EM2 MQTT entities creation, also the Phase A-C entities are still being created with the script. The EM ones appears correctly, the Phase A-C appears as unknown, like it was in the previous version.
image

**Comment by bieniu** [comment]
You have to remove those entities manually from MQTT broker (topics `homeassistant/sensor/xxxxx/config`), I'm not able to remove them from the script.

**Comment by jpatriarca** [comment]
Thanks, done it. But still, most of my Gen2 devices are not getting some entities, like Diagnostics, Configuration and Events (sensos and controls seems to be working). I'll figure it out. Thanks

**Comment by bieniu** [comment]
If you can't solve the problem, open the issue and attach a debug log.

**Pull request merged**
