### PR TITLE
Add support for BLU H&T

### PR DESCRIPTION
**Pull request by bieniu**
Relates to https://github.com/bieniu/ha-shellies-discovery-gen2/issues/461

### CODE REVIEW

**Comment by Bo1jo** [comment]
Are there any additional changes in the device settings or in the home assistant automation settings that’s required to discover the BLU H&T? I have a BLU H&T, connected via Shelly Plug S Gen 3, but it’s not discovered when running the updated script.

The Shelly Plug is discovered by the script and the Plug has Bluetooth enabled (RPS and Bluetooth gateway enabled). The BLU H&T is reporting data to Shelly Cloud via the Shelly Plug as BLE Observer.

**Comment by bieniu** [comment]
image

**Comment by Spartacus68** [comment]
Hi,

I have issues to add the BLU H&T devices. I have checked announceGen2 and discoveryGen2 scipts and they are up2date. The device (mini1Gen3) is detected in HA and the scriot on the shelly is installed.

I can see in the mqttExplorer that bthomedevice status is sent by the device, but in HA nothing is available in HA. Is there a trick to add the BT Devices in HA? Is there addditional configuration in the announceGen2 script necessary?

BTHomeIntegration is installed and is working with shelly integration and annother mini1Gen3 which is bound to HA via shelly integration.

**Comment by bieniu** [comment]
@Spartacus68 Look up

**Pull request merged**
